### ISSUE TITLE
How to create object literals

### ISSUE THREAD

**Issue by marians** [crate/crate-python#146]
According to https://crate.io/docs/stable/sql/data_types.html#object-literals, when inserting objects into a Crate table, an object literals notation is required.

For a developer using the Python `crate` module the question is how to generate these literals.

I can't find any example in the docs or test where this is done, so I assume I currently have to take care of this myself. Then my question is: is there a convenient module out there to simplify this?

**Comment by mfussenegger** [comment]
You can just pass python dictionaries as arguments. E.g.

```python
from crate.client import connect

conn = connect()
c = conn.cursor()

c.execute('create table t (obj object)')
c.execute('insert into t (obj) values (?)', ({"a": 1},))
```

Thanks for pointing out that it is missing from the docs. We'll improve that.

**Comment by marians** [comment]
> You can just pass python dictionaries as arguments

Thanks for the quick reply, that sounds awesome! This is what I assumed first, since it would be just the most pythonic way. I tried that, then ran into an error. So I'll go back to investigating that error.
