### ISSUE TITLE
How to return all records?

### ISSUE THREAD

**Issue by Broham** [crate/crate-python#251]
Currently when I do `cursor.fetchall()` it's stoping at 10,000 records.  I need access to all records - how can I remove this limitation?

**Comment by chaudum** [comment]
Hi @Broham 
10_000 is an [internal limit in CrateDB](https://crate.io/docs/crate/reference/en/latest/general/dql/selects.html#limits) to prevent the clients that use HTTP from loading loads of data into memory.
You can simply increase the limit with a `LIMIT x` clause in your query, but be aware of the memory implication.
