### ISSUE TITLE
SqlAlchemy unable to map cratedb long and double data types.

### ISSUE THREAD

**Issue by AKNiazi** [crate/crate-python#252]
I want to create new table in cratedb with one column of type long and other of type double using Sqlalchemy. I mapped long and double data types to Sqlalchemy's NUMERIC and DECIMAL data types as stated [here](https://crate.io/docs/clients/python/en/latest/sqlalchemy.html). But they are not getting converted to long and double. Following is my code snippet.

         meta = MetaData(self.get_sqla_engine())
         Table('user', metadata,
             Column('id', Integer, primary_key=True),
             Column('user_name', String(), nullable=False),
             Column('num', DECIMAL(), nullable=False),
             Column('num2', NUMERIC(), nullable=False)
         )

         table = Table(datasource, meta, *columns)
         meta.create_all()

The sql query it creates is

         CREATE TABLE user (
                 id INT, 
                 user_name STRING,
                 num DECIMAL,
                 num2 NUMERIC, 
            PRIMARY KEY (id)
       );

As numeric and decimal are not supported cratedb types, cratedb throws error.

**Comment by matriv** [comment]
Issue has been fixed and released with 0.21.1
