### ISSUE TITLE
feature request:Whether the support with Geo data types within the SQLAlchemy?

### ISSUE THREAD

**Issue by Andyworker** [crate/crate-python#273]
### Hey, your repos is awnsome, am i thx for u

Don't find the `Geo` data types in the `SQLAlchemy` when am I process the some works, but in the `crate.io` home website's documents, I saw the support the `Geo` type(see this [Geo-pointer](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#geo-point)),

_Are you planning the support the type or Am i help for you with resolution it_

**Comment by mfussenegger** [comment]
We currently don't have a extra sqlalchemy type for the `geo_point` or `geo_shape` types. You could take a look at how we implemented `Object` support (https://github.com/crate/crate-python/blob/master/src/crate/client/sqlalchemy/types.py#L144)

Or use raw sql to utilize `geo_point` or `geo_shape` columns.

We'd be happy to accept contributions for this.

**Comment by Andyworker** [comment]
thx you feed back, I Can try be implement `GEO` data type and commit it

**Comment by autophagy** [comment]
@Andyworker Support for both geo point and geo shape types have been added to the SQLA dialect. I will close this issue, please feel free to reopen it if you spot anything! :slightly_smiling_face:
