### ISSUE TITLE
Not able to insert GeoPoint

### ISSUE THREAD

**Issue by robd003** [crate/crate-python#300]
I'm trying to insert a geopoint using a python list containing two floating points. However I receive this error:

crate.client.exceptions.ProgrammingError: SQLActionException[ColumnValidationException: Validation failed for pin: Cannot cast [37.751, -97.822] to type geo_point]

**Comment by chaudum** [comment]
`-97.822` is not a valid value for latitude. the format of the geo_point is `[lon, lat]` (see [docs](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#geo-point))
