### ISSUE TITLE
The following error occurred while using crate under superset

### ISSUE THREAD

**Issue by javyxu** [crate/crate-python#307]
When I use cratedb under superset, the following error will occur when only adding tables.How to solve it?
![image](https://user-images.githubusercontent.com/22185273/46007998-0dbc6500-c0ee-11e8-97e5-da42a1ed39fa.png)

**Comment by jodok** [comment]
thanks for trying it @javyxu :) is there a chance you can find out the failing query?
either in superset, or by `set global stats.enabled=true` and looking at `sys.jobs_log`?

**Comment by jodok** [comment]
we would need the sql statement, not the python traceback...

**Comment by javyxu** [comment]
**Are these what you want to see？**

![image](https://user-images.githubusercontent.com/22185273/46050548-5a905200-c167-11e8-88f0-d1fcea276a4e.png)

**Here's his details：**
DEBUG:crate.client.http:JSON response for stmt(SELECT column_name
                    FROM information_schema.key_column_usage
                    WHERE table_name = ? AND table_catalog = ?): {'cols': ['column_name'], 'rows': [], 'rowcount': 0, 'duration': 0.627271}

**Comment by joemoe** [comment]
hi @javyxu, we don't support the `key_column_usage` table in the `information_schema` schema. i added this to our backlog and will get back to you once this is released. as we are constantly increasing our postgresql compatibility this is something is of interest to us.
thanks, joe

**Comment by kovrus** [comment]
Hi @javyxu,

You can use Superset with CrateDB ( >=3.2) using its [crate-python](https://github.com/crate/crate-python) client.

Please note that if a source's table contains timestamp columns, you would have to edit the table metadata and explicitly provide the datatime format for those columns.

![image](https://user-images.githubusercontent.com/7442373/55147463-b81d4f80-5146-11e9-9203-18786f3b3ac5.png)

**Comment by javyxu** [comment]
OK, Thank you!
