### ISSUE TITLE
Issue in Connection timeout when CrateDB is not available

### ISSUE THREAD

**Issue by daminichopra** [crate/crate-python#339]
I am using CrateDb for my application but facing an issue while receiving a notification, if the DB isn't available then it returns **500 Internal Error** quickly.
 CrateDb  has no retry interval between total retries. So, i suggest that CrateDb should wait for certain time between retries and do not return result immediately.

As per my analysis, the  parameter [**"backoff_factor"**](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html) is defined in crateDB, which is used to define the time-interval between consecutive retries. The default value of **backoff_factor** can be assigned as **"0.0"**  and it can be changed as per requirement.
I am using CrateDb version : 3.1.2

Also, Please find attached logs for the same.
![image](https://user-images.githubusercontent.com/35693908/73639842-2e59df00-4693-11ea-941f-d6b42d13932c.png)
![image](https://user-images.githubusercontent.com/35693908/73639852-34e85680-4693-11ea-831e-f7f47c5782bc.png)

In reference to following [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/242).

**Comment by daminichopra** [comment]
Hi @autophagy , As i wanted the solution for this issue urgently and i have already fixed the code so can i raise the PR for the same that it can be closed as soon as possible. Please confirm. Thank you

**Comment by mariacrate** [comment]
Hi @daminichopra.
Thanks for raising this subject. We're very pleased CrateDB supports your application. We would be glad to assist you further with the issue you're struggling. Please feel free to share your contact details and I will be back with you shortly. Also, you can reach me out directly at maria@crate.io
I look forward to hearing from you soon!
Maria

**Comment by daminichopra** [comment]
Hi @autophagy , I have fixed the code in cratedb. Now , i want to test code locally for which i am using pytest but test cases are not running.
Can you please guide me for the steps on how to run test cases in crateDB.
Thank you :)

**Comment by mfussenegger** [comment]
> 
> 
> Hi @autophagy , I have fixed the code in cratedb. Now , i want to test code locally for which i am using pytest but test cases are not running.
> Can you please guide me for the steps on how to run test cases in crateDB.
> Thank you :)

This project currently uses the zope testrunner, see [Running Tests](https://github.com/crate/crate-python/blob/master/DEVELOP.rst#running-tests) in our developer docs.

**Comment by autophagy** [comment]
Fixed with #344
