### ISSUE TITLE
connection fails when trying to connect with verfiy_ssl_cert=True

### ISSUE THREAD

**Issue by proddata** [crate/crate-python#389]
Trying to connect to a CrateDB Cloud cluster with the default pyhton example currently fails, as the option `verfiy_ssl_cert=True` doesn't work. It seems like the client is looking for a local certificate, although the (valid) certificate from the cloud cluster is signed by a public/trusted certificate

```python
from crate import client

conn = client.connect("https://<cluster>.cratedb.net:4200", username="<user>", password="<password>$", verify_ssl_cert=True)
with conn:
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sys.cluster")
    result = cursor.fetchone()
    print(result)
e
```

Error
```sh
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```

**Comment by mfussenegger** [comment]
Might be related to your python installation and outdated ca bundles.

We could consider to add certifi as optional dependency.
See https://github.com/urllib3/urllib3/blob/ccf907904d042625291472fe7a85971b62037948/docs/user-guide.rst#certificate-verification

**Comment by proddata** [comment]
after refreshing the python installation and uninstalling crash/crate it seems like the problems are gone.
Maybe worth trying on a fresh installed macOS.

Though since I can't recreate the problem, I will close the issue.
